services:
  backend:
    env_file: .env
    image: mnogom/bash-backend:latest
    hostname: freidlin
    dns: ["0.0.0.0"]
    restart: always
    networks:
      - bash-network

  nginx:
    image: mnogom/bash-frontend:latest
    restart: always
    ports:
      - 80:80
    networks:
      - bash-network

networks:
  bash-network: