services:
  backend:
    container_name: backend
    env_file: .env
    image: mnogom/bash-backend:latest
    hostname: freidlin
    dns: ["0.0.0.0"]
    restart: always
    networks:
      - bash-network

  nginx:
    container_name: nginx
    build:
      context: ./bash-frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - bash-network
    volumes:
      # - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro

  certbot:
    container_name: certbot
    image: certbot/certbot:v2.11.0
    depends_on:
      - nginx
    networks:
        - bash-network
    volumes:
      - ./certbot/www/:/var/www/certbot:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  bash-network:
