services:
  backend:
    container_name: backend
    env_file: .env
    image: mnogom/bash-backend:latest
    hostname: freidlin
    dns: ["0.0.0.0"]
    restart: always
    networks:
      - bash-network
    volumes:
      - ./bash-volume:/home/konstantin:ro

  nginx:
    container_name: nginx
    image: mnogom/bash-frontend-no-ssl:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./certbot/www/:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    networks:
      - bash-network

networks:
  bash-network:
