services:
  backend:
    container_name: backend
    env_file:
      - ./bash-backend/.env
    build:
      context: ./bash-backend
      dockerfile: Dockerfile
      target: production
    hostname: freidlin
    dns: ["0.0.0.0"]
    networks:
      - bash-network

  nginx:
    container_name: nginx
    build:
      context: ./bash-frontend
      dockerfile: Dockerfile
      target: no-ssl
    ports:
      - 80:80
    networks:
      - bash-network

networks:
  bash-network:
